language: cpp
compiler: g++

install:

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    
script: 
  - cd MQTTSNGateway
  - make CXX="g++-4.8" SENSORNET="xbee"
  - make CXX="g++-4.8" SENSORNET="udp"
  - make CXX="g++-4.8" SENSORNET="udp6"
  - make test
    
  - cd GatewayTester
  - make CXX="g++-4.8"
 
  
notifications:
  emails:
    - tomoaki@tomy-tech.com
    
